#!/bin/sh
#
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

branch=$(git branch --show-current)
[ "$branch" = "gh-pages" ] && exit 0
echo Launching pytest...
poetry run pytest tests
status=$?
[ $status -eq 0 ] && echo "tests successful" || (echo Tests failed! >&2; exit $status)
